# Change leader key
unbind C-b

set -g prefix C-x
bind C-x send-prefix

# Set TMUX refresh key
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

#### Tmux Plugin Manager Configuration ####
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'odedlaz/tmux-onedark-theme'

source-file ~/.config/tmux/conf/ui/*.conf
source-file ~/.config/tmux/conf/plugins/*.conf
source-file ~/.config/tmux/conf/core/*.conf

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
